# ══════════════════════════════════════════════════════════════
# news_conteudo.py — Conteúdo escrito do Orange News (seções que trocam todo dia).
# Para ampliar o jornal, basta acrescentar itens nas listas abaixo: cada categoria
# entra na edição de forma rotativa (um item por categoria por dia).
# `recurso` (opcional) = aba do app que o leitor pode abrir pelo botão "Experimente no app":
#   avaliacao, estudo, afinador, acordes, biblioteca, historico, composicoes, conversor,
#   producao, edicao, songwriter, estudio (painel do Orange Studio).
# ══════════════════════════════════════════════════════════════

ROTULOS = {
    "afinacao": "Afinação & Voz",
    "composicao": "Composição & Temas",
    "violao": "Violão & Levadas",
    "teoria": "Teoria em 1 minuto",
    "producao": "Produção Musical",
    "ia": "IA & Música",
    "curiosidade": "Curiosidades",
}

# Editoria de destaque de cada dia da semana (segunda = 0)
EDITORIA_DA_SEMANA = ["afinacao", "composicao", "violao", "teoria", "producao", "ia", "curiosidade"]

ITENS = {
    "afinacao": [
        {"titulo": "Comece o treino de afinação por uma nota só",
         "texto": "Antes de cantar frases inteiras, sustente uma única nota por 5 segundos e olhe o desvio em cents. Um semitom tem 100 cents, e ficar dentro de uns 20 cents costuma soar afinado para a maioria dos ouvidos. Repita em três notas da sua região confortável.",
         "recurso": "estudo"},
        {"titulo": "Grave-se: o ouvido de quem canta engana",
         "texto": "Quando cantamos, ouvimos a própria voz pelo ar e também pela vibração dos ossos da cabeça, e por isso a gravação soa diferente. Grave 30 segundos, ouça sem cantar junto e só depois olhe os números da análise.",
         "recurso": "estudo"},
        {"titulo": "Aquecimento de 5 minutos",
         "texto": "Sirene (deslizar do grave ao agudo), vibração de lábios e cantarolar de boca fechada preparam a voz sem forçar. Comece baixinho e vá ampliando a região aos poucos. O exercício de glissando da Avaliação é uma sirene.",
         "recurso": "avaliacao"},
        {"titulo": "Hidratação vale mais que gargarejo",
         "texto": "A água que você bebe chega às pregas vocais pelo corpo, e não pela garganta, então o efeito é de horas e não de minutos. Beba ao longo do dia, e não só na hora de cantar.",
         "recurso": None},
        {"titulo": "Desafinou sempre pra baixo ou pra cima? É uma pista",
         "texto": "Tendência para baixo costuma vir de pouco apoio de ar ou de garganta baixa e cansada. Tendência para cima costuma aparecer quando se força para alcançar a nota. O card \"Tendência\" da análise mostra qual é a sua.",
         "recurso": "estudo"},
        {"titulo": "Vibrato: 5 a 7 oscilações por segundo",
         "texto": "O vibrato natural fica em torno de 5 a 7 oscilações por segundo e nasce de uma voz relaxada e apoiada. Se for forçado, vira tremor. A análise mostra a taxa e a extensão do seu vibrato.",
         "recurso": "estudo"},
    ],
    "composicao": [
        {"titulo": "Comece pelo título",
         "texto": "Muitas canções nascem de uma frase forte que vira título e refrão. Escreva 10 títulos em 5 minutos, escolha o que dá vontade de cantar e construa a letra ao redor dele.",
         "recurso": "songwriter"},
        {"titulo": "O verso conta, o refrão resume",
         "texto": "Use o verso para mostrar detalhes concretos (lugares, objetos, cenas) e o refrão para dizer a ideia central em poucas palavras. Refrões curtos e repetidos ficam na memória.",
         "recurso": "composicoes"},
        {"titulo": "Prosódia: a sílaba forte na nota forte",
         "texto": "A palavra \"saudade\" tem a força em \"da\" (sau-DA-de). Ela soa natural quando essa sílaba cai num tempo forte ou numa nota mais longa. Quando a acentuação da fala briga com a melodia, a letra soa estranha.",
         "recurso": "composicoes"},
        {"titulo": "Três temas que quase sempre funcionam",
         "texto": "Despedida, recomeço e lugar de origem. Quase todo mundo já viveu algo assim, e o ouvinte se enxerga na história. Conte um momento só (uma cena) em vez da história inteira.",
         "recurso": "songwriter"},
        {"titulo": "Uma progressão de 4 acordes para começar",
         "texto": "A sequência I–V–vi–IV (em Dó: C, G, Am, F) sustenta milhares de canções. Use como base para testar melodias e depois troque um só acorde para surpreender.",
         "recurso": "acordes"},
        {"titulo": "Melodia primeiro ou letra primeiro?",
         "texto": "Não há regra. Quem começa pela melodia costuma cantar sílabas soltas (\"la la\") para achar o desenho; quem começa pela letra precisa testar o ritmo das frases cantando. Alterne os métodos para descobrir o seu.",
         "recurso": "composicoes"},
    ],
    "violao": [
        {"titulo": "Troque de acorde antes do tempo",
         "texto": "Nas trocas, mova os dedos no último instante do compasso anterior, sem parar de tocar. Treine com dois acordes e o metrônomo lento, e só acelere quando as trocas ficarem limpas.",
         "recurso": "acordes"},
        {"titulo": "Capotraste: o atalho de quem canta",
         "texto": "Se o tom está alto ou baixo demais para a sua voz, o capotraste muda o tom sem mudar as formas de acorde que você já sabe. Cada casa sobe um semitom.",
         "recurso": "acordes"},
        {"titulo": "Pestana sem sofrimento",
         "texto": "Apoie a lateral do dedo indicador, e não a parte mole do meio, e use o peso do braço em vez de apertar com o polegar. Se ainda abafar, posicione o dedo mais perto do traste.",
         "recurso": None},
        {"titulo": "Palm mute em uma frase",
         "texto": "Encoste a lateral da mão direita perto da ponte, sobre as cordas graves, para abafar levemente. Dá aquele som seco e marcado de rock e pop.",
         "recurso": None},
        {"titulo": "Dedilhado básico: polegar no baixo",
         "texto": "Polegar nas cordas graves; indicador na 3ª, médio na 2ª e anular na 1ª. Toque o baixo primeiro e depois as agudas, devagar, até o movimento ficar automático.",
         "recurso": None},
        {"titulo": "Aprenda a levada com a boca",
         "texto": "Antes de tocar, fale o ritmo (\"tum ta-ta tum ta\") batendo no joelho. Se você consegue falar, consegue tocar: a mão só executa o que o ouvido já conhece.",
         "recurso": None},
    ],
    "teoria": [
        {"titulo": "Relativa menor: o gêmeo triste",
         "texto": "Toda escala maior tem uma menor com as mesmas notas, começando no 6º grau. Dó maior e Lá menor usam as mesmas notas, e por isso Am, F, C e G convivem tão bem.",
         "recurso": "acordes"},
        {"titulo": "Pentatônica: por que é difícil errar",
         "texto": "A pentatônica maior não tem o 4º nem o 7º grau, justamente os que criam tensão. Sem semitons, ela encaixa em muitos acordes. Ótima para improvisar e para treinar saltos de terça na voz.",
         "recurso": "estudo"},
        {"titulo": "Modos: mude só uma nota",
         "texto": "O lídio é a escala maior com o 4º grau aumentado; o mixolídio é a maior com a 7ª menor; o dórico é a menor com a 6ª maior. Cantar um modo é sentir o que mudou na melodia.",
         "recurso": "estudo"},
        {"titulo": "Acorde sus: nem alegre, nem triste",
         "texto": "O sus2 e o sus4 trocam a terça por outra nota e deixam o acorde em suspenso. Servem para criar clima antes de resolver num acorde maior ou menor.",
         "recurso": "acordes"},
        {"titulo": "Círculo das quintas em 30 segundos",
         "texto": "Cada passo no sentido horário sobe uma quinta e acrescenta um sustenido na armadura (Dó, Sol, Ré…). Tonalidades vizinhas dividem muitos acordes, e por isso modulam com facilidade.",
         "recurso": None},
        {"titulo": "Tensão e resolução: o V7",
         "texto": "O acorde de dominante (V7) tem um trítono que pede resolução na tônica. Em Dó maior, o G7 (com o Si e o Fá) puxa para o C. É a base da sensação de chegada.",
         "recurso": "acordes"},
    ],
    "producao": [
        {"titulo": "Filtre o grave que a voz não usa",
         "texto": "Um filtro passa-alta em torno de 80 a 100 Hz na voz tira o ruído de manuseio e o rumble sem mexer no timbre. Ouça o antes e o depois.",
         "recurso": "edicao"},
        {"titulo": "Compressão: pouca, e com o ouvido",
         "texto": "Uma compressão suave (algo como 2:1 a 4:1) uniformiza a voz sem esmagar a dinâmica. Se você já escuta o compressor trabalhando, provavelmente exagerou.",
         "recurso": "edicao"},
        {"titulo": "Reverb: menos do que parece",
         "texto": "Um reverb leve dá espaço, mas demais empurra a voz para o fundo da mixagem. Ajuste até quase não notar e depois desligue: se você sente falta, está no ponto.",
         "recurso": "edicao"},
        {"titulo": "Deixe espaço no master",
         "texto": "Antes de masterizar, mantenha os picos da mixagem por volta de −6 dB. Isso dá margem a quem masteriza e evita distorção. O volume alto se conquista depois.",
         "recurso": "producao"},
        {"titulo": "Ouça a mixagem em três lugares",
         "texto": "Confira no fone, na caixa do celular e no carro. Se funciona nos três, funciona em quase qualquer lugar.",
         "recurso": None},
        {"titulo": "Ducking: abrir espaço para a voz",
         "texto": "Baixar levemente os instrumentos enquanto a voz canta libera espaço nas frequências da fala. A Produção do app usa esse recurso no modo \"qualidade profissional\".",
         "recurso": "producao"},
    ],
    "ia": [
        {"titulo": "Use a IA como parceira, não como autora",
         "texto": "Peça cinco versões de um refrão, pegue só a melhor linha de cada uma e reescreva com as suas palavras. O resultado fica mais seu e menos genérico.",
         "recurso": "songwriter"},
        {"titulo": "Um prompt musical que funciona",
         "texto": "Descreva gênero, andamento, instrumentos e clima numa frase: \"balada pop lenta, violão de nylon, voz feminina suave, clima nostálgico\". Prompts curtos e específicos costumam render mais que listas longas.",
         "recurso": "songwriter"},
        {"titulo": "Separar stems abre um mundo",
         "texto": "Com voz e instrumental separados, você treina cantando sobre a base, estuda o baixo isolado ou faz um remix. No Orange Studio, a separação roda no Colab.",
         "recurso": "estudio"},
        {"titulo": "Privacidade: para onde vai o seu áudio?",
         "texto": "Alguns serviços gratuitos de IA, como o nível gratuito da API do Gemini, podem usar o conteúdo enviado para melhorar seus produtos e permitir revisão humana. Se a música é inédita ou pessoal, confira os termos antes de enviar.",
         "recurso": None},
        {"titulo": "Direitos autorais e música gerada por IA",
         "texto": "As regras sobre músicas geradas por IA mudam de país para país e de plataforma para plataforma. Antes de publicar ou monetizar, leia os termos do serviço que você usou e prefira partir de material seu.",
         "recurso": None},
        {"titulo": "A IA como ouvido de apoio",
         "texto": "Um bom uso da IA é ter um segundo par de ouvidos: a Laranjinha pode ouvir a sua gravação e comentar, e a aba Acordes identifica o acorde que você montou no braço.",
         "recurso": "acordes"},
    ],
    "curiosidade": [
        {"titulo": "1 semitom = 100 cents",
         "texto": "Cada semitom se divide em 100 cents, e uma oitava tem 1.200. Ouvidos treinados percebem diferenças de uns 5 a 10 cents em notas isoladas, e por isso a afinação fina é uma habilidade treinável.",
         "recurso": "estudo"},
        {"titulo": "O Lá 440 Hz não é universal",
         "texto": "É o padrão moderno, mas muitas orquestras usam 442 Hz, e a música barroca tocada com instrumentos de época costuma usar cerca de 415 Hz. O app deixa você escolher entre 440 e 442.",
         "recurso": "afinador"},
        {"titulo": "A pentatônica está no mundo todo",
         "texto": "Escalas de cinco notas aparecem em músicas de culturas muito diferentes, da China à Escócia e ao blues. Por isso soam familiares para quase qualquer ouvinte.",
         "recurso": "estudo"},
        {"titulo": "A terça escondida do violão",
         "texto": "A afinação padrão (Mi, Lá, Ré, Sol, Si, Mi) usa intervalos de quarta entre as cordas, exceto entre a 3ª e a 2ª (Sol e Si), que é uma terça maior. É um compromisso que deixa muitas formas de acorde confortáveis para a mão.",
         "recurso": "afinador"},
        {"titulo": "Quantas vezes suas pregas vibram?",
         "texto": "Quando você canta o Lá de 440 Hz, as pregas vocais abrem e fecham cerca de 440 vezes por segundo.",
         "recurso": "estudo"},
        {"titulo": "O piano tem 88 teclas",
         "texto": "Vão do Lá mais grave (A0) ao Dó mais agudo (C8), pouco mais de sete oitavas.",
         "recurso": None},
    ],
}

# Levadas de violão. Cada coluna é uma colcheia; a 1ª linha do painel mostra "1 e 2 e 3 e 4 e" (ou "1 e 2 e 3 e").
LEVADAS = [
    {"nome": "Pop clássica (4/4)", "contagem": ["1", "e", "2", "e", "3", "e", "4", "e"],
     "golpes": ["↓", "", "↓", "↑", "", "↑", "↓", "↑"],
     "dica": "A mão continua o movimento de vai-e-vem o tempo todo; nos espaços em branco ela passa sem tocar as cordas. Serve para milhares de canções.", "recurso": "acordes"},
    {"nome": "Colcheias contínuas (rock e pop rápido)", "contagem": ["1", "e", "2", "e", "3", "e", "4", "e"],
     "golpes": ["↓", "↑", "↓", "↑", "↓", "↑", "↓", "↑"],
     "dica": "Um golpe para baixo em cada tempo e um para cima em cada \"e\". Acentue o baixo do 1 e do 3 para dar direção.", "recurso": "acordes"},
    {"nome": "Balada (um golpe por tempo)", "contagem": ["1", "e", "2", "e", "3", "e", "4", "e"],
     "golpes": ["↓", "", "↓", "", "↓", "", "↓", ""],
     "dica": "Deixe o acorde soar e cante por cima. Ótima para conferir a afinação da voz sobre uma base simples.", "recurso": "estudo"},
    {"nome": "Reggae (contratempos)", "contagem": ["1", "e", "2", "e", "3", "e", "4", "e"],
     "golpes": ["", "↑", "", "↑", "", "↑", "", "↑"],
     "dica": "O acorde soa só nos contratempos, curto e abafado; o espaço deixado nos tempos é o que dá o balanço.", "recurso": "acordes"},
    {"nome": "Country (\"boom-chick\")", "contagem": ["1", "e", "2", "e", "3", "e", "4", "e"],
     "golpes": ["baixo", "", "acorde", "", "baixo", "", "acorde", ""],
     "dica": "Nos tempos 1 e 3 toque só a nota grave do acorde (a fundamental, e depois a quinta); nos tempos 2 e 4, o acorde inteiro.", "recurso": "acordes"},
    {"nome": "Valsa (3/4)", "contagem": ["1", "e", "2", "e", "3", "e"],
     "golpes": ["baixo", "", "↓", "", "↓", ""],
     "dica": "Um baixo forte no 1 e dois golpes leves de acorde no 2 e no 3: \"um-dois-três, um-dois-três\".", "recurso": "acordes"},
]
